# Each entry must have three fields:
#   number -> binary host number which must be unique for each host
#   spaceNorm multiplies the free space in GBs by this value then converts that to a uint16
#   tempNorm multiplies the temperature in milliC by this value then to a uint16
#
# For spaceNorm   
#   128GB potential -> 511
#   256GB potential -> 255
#   4TB potential -> 16
#
# For tempNorm
#   100C -> 0.65
#
pe0: {"number": 0, "spaceNorm": 511, "tempNorm": 0.65}
pe1: {"number": 1, "spaceNorm": 511, "tempNorm": 0.65}
pe2: {"number": 2, "spaceNorm": 256, "tempNorm": 0.65}
ps0: {"number": 3, "spaceNorm": 511, "tempNorm": 0.65}
ps1: {"number": 4, "spaceNorm": 511, "tempNorm": 0.65}
ps2: {"number": 5, "spaceNorm": 256, "tempNorm": 0.65}
shore0: {"number": 6, "spaceNorm": 255, "tempNorm": 0.65}
Patricio-M1.local: {"number": 255, "spaceNorm": 16, "tempNorm": 0.65}
